[versions]
# plugins
dokka = "2.0.0"
gradlePluginPublish = "1.3.1"
gradleChangelogPlugin = "2.4.0"

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
