[versions]
# plugins
dokka = "2.1.0"
gradlePluginPublish = "2.0.0"
gradleChangelogPlugin = "2.2.1"

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
